# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1
FROM node:lts-alpine

# Create app directory
WORKDIR /usr/src/app

# Install dependencies
COPY package.json package-lock.json tsconfig.json ./
COPY src ./src

RUN npm install --ignore-scripts
RUN npm run build

# Default environment variables
ENV DOMAIN="u301.co"
# U301_API_KEY must be provided

# Start command
CMD ["node", "build/index.js"]
